# Base configs
baseurl: "https://lukasphotographyportfolio.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Lukas Campbell"
subtitle: "See the world through my eyes!"
author: "Lukas Campbell"
bio: 
theme: jekyll-theme-cayman
